export const quiz = {
  totalQuestions: 60,
  questions: [
    {
      id: 1,
      question: "What should be produced in an economy?",
      answers: [
        "Consumer Goods",
        "Capital Goods",
        "Services",
        "All of the above",
      ],
        correctAnswer: "All of the above",
    },
    {
      id: 2,
      question: "How should limited budgets be managed?",
      answers: [
        "Increasing income",
        "Reducing expenses",
        "Both A and B",
        "Neither A nor B",
      ],
      correctAnswer: "Both A and B",
    },
    {
      id: 3,
      question: "How can access to medicines be expanded?",
      answers: [
        "Lowering prices",
        "Increasing production",
        "Improving distribution",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 4,
      question: "What is a key strategy to stop infectious diseases?",
      answers: ["Vaccination", "Isolation", "Sanitation", "All of the above"],
      correctAnswer: "All of the above",
    },
    {
      id: 5,
      question: "What measures can increase the literacy rate in Pakistan?",
      answers: [
        "Better schools",
        "Qualified teachers",
        "Free education",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 6,
      question: "Which subject areas should education focus on more?",
      answers: ["Science", "Technology", "Engineering", "All of the above"],
      correctAnswer: "All of the above",
    },
    {
      id: 7,
      question: "Why is the number of vehicles growing?",
      answers: [
        "Population growth",
        "Economic growth",
        "Urbanization",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 8,
      question: "What are some reasons for increasing accidents on motorways?",
      answers: [
        "Speeding",
        "Distracted driving",
        "Poor road conditions",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 9,
      question: "How can mobile banking transactions be secured?",
      answers: [
        "Encryption",
        "Two-factor authentication",
        "Regular updates",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 10,
      question: "Why do websites show unwanted advertisements?",
      answers: [
        "Revenue generation",
        "Targeted marketing",
        "Lack of ad blockers",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 11,
      question: "How do 5G cell phone signals potentially harm humans?",
      answers: [
        "Radiation exposure",
        "Interference with medical devices",
        "Biological effects",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 12,
      question: "How do trees give Earth all its oxygen?",
      answers: [
        "Photosynthesis",
        "Respiration",
        "Transpiration",
        "All of the above",
      ],
      correctAnswer: "Photosynthesis",
    },
    {
      id: 13,
      question: "What is a common economic problem?",
      answers: ["Scarcity", "Inflation", "Unemployment", "All of the above"],
      correctAnswer: "Scarcity",
    },
    {
      id: 14,
      question: "What can help manage limited budgets in healthcare?",
      answers: [
        "Efficient resource allocation",
        "Cost-effective treatments",
        "Preventive care",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 15,
      question: "What is a major challenge in education?",
      answers: [
        "Quality of teaching",
        "Access to education",
        "Curriculum development",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 16,
      question: "What are the benefits of improved transportation?",
      answers: [
        "Reduced travel time",
        "Lower costs",
        "Increased safety",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 17,
      question: "What are some solutions to internet security issues?",
      answers: [
        "Firewalls",
        "Antivirus software",
        "Secure passwords",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 18,
      question: "What is a significant problem in biology?",
      answers: [
        "Disease",
        "Environmental impact",
        "Genetic disorders",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 19,
      question: "How can economic problems be addressed?",
      answers: [
        "Policy changes",
        "Innovation",
        "Education",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 20,
      question: "What strategies can improve healthcare access?",
      answers: [
        "Telemedicine",
        "Community clinics",
        "Mobile health units",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 21,
      question: "How can education systems be improved?",
      answers: [
        "Teacher training",
        "Updated curriculum",
        "Technology integration",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 22,
      question: "What factors contribute to transportation issues?",
      answers: [
        "Traffic congestion",
        "Pollution",
        "Infrastructure",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 23,
      question: "How can internet security be enhanced?",
      answers: ["Education", "Technology", "Regulation", "All of the above"],
      correctAnswer: "All of the above",
    },
    {
      id: 24,
      question: "What are the key areas of study in biology?",
      answers: ["Genetics", "Ecology", "Microbiology", "All of the above"],
      correctAnswer: "All of the above",
    },
    {
      id: 25,
      question: "What are the economic implications of an aging population?",
      answers: [
        "Increased healthcare costs",
        "Pension system strain",
        "Labor market changes",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 26,
      question: "What can be done to improve patient outcomes in healthcare?",
      answers: [
        "Early diagnosis",
        "Personalized medicine",
        "Preventive care",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 27,
      question: "How can literacy rates be improved?",
      answers: [
        "Adult education programs",
        "Childhood literacy initiatives",
        "Government policies",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 28,
      question: "What are the consequences of transportation pollution?",
      answers: [
        "Economic loss",
        "Health problems",
        "Environmental damage",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 29,
      question: "What are the main threats to internet security?",
      answers: ["Hackers", "Malware", "Phishing", "All of the above"],
      correctAnswer: "All of the above",
    },
    {
      id: 30,
      question: "What role does biology play in medicine?",
      answers: [
        "Understanding diseases",
        "Developing treatments",
        "Improving health",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 31,
      question: "What is a common issue in economic policy?",
      answers: [
        "Balancing budgets",
        "Stimulating growth",
        "Controlling inflation",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 32,
      question: "How can healthcare be made more affordable?",
      answers: [
        "Subsidies",
        "Insurance reforms",
        "Cost control",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 33,
      question: "What are effective methods of teaching?",
      answers: [
        "Interactive learning",
        "Practical applications",
        "Collaborative projects",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 34,
      question: "What can reduce transportation pollution?",
      answers: [
        "Electric vehicles",
        "Public transportation",
        "Carpooling",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 35,
      question: "What are common internet security practices?",
      answers: [
        "Strong passwords",
        "Regular updates",
        "Two-factor authentication",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 36,
      question: "What is an important focus in biology research?",
      answers: [
        "Genetic engineering",
        "Climate change",
        "Public health",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 37,
      question: "How does economic inequality affect society?",
      answers: [
        "Increased crime",
        "Poor health outcomes",
        "Lower educational attainment",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 38,
      question: "What is a common challenge in economic development?",
      answers: [
        "Infrastructure",
        "Education",
        "Healthcare",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 39,
      question: "How can public health systems be strengthened?",
      answers: [
        "Increased funding",
        "Better policies",
        "Community involvement",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 40,
      question: "What can improve teacher effectiveness?",
      answers: [
        "Professional development",
        "Better resources",
        "Smaller class sizes",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 41,
      question: "What are some solutions to traffic congestion?",
      answers: [
        "Improved public transport",
        "Traffic management",
        "Urban planning",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 42,
      question: "What are common issues with online privacy?",
      answers: [
        "Data breaches",
        "Tracking",
        "Identity theft",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 43,
      question: "What are some environmental impacts of deforestation?",
      answers: [
        "Loss of biodiversity",
        "Climate change",
        "Soil erosion",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 44,
      question: "What strategies can help reduce healthcare disparities?",
      answers: [
        "Equitable access",
        "Cultural competence",
        "Policy changes",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 45,
      question: "How can educational technology enhance learning?",
      answers: [
        "Interactive tools",
        "Access to resources",
        "Personalized learning",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 46,
      question: "What are the effects of urbanization on transportation?",
      answers: [
        "Increased congestion",
        "Higher pollution",
        "Better infrastructure",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 47,
      question: "How can internet service be improved?",
      answers: [
        "Infrastructure upgrades",
        "Increased competition",
        "Better regulation",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 48,
      question: "What are the main sources of renewable energy?",
      answers: ["Solar", "Wind", "Hydropower", "All of the above"],
      correctAnswer: "All of the above",
    },
    {
      id: 49,
      question: "What can be done to enhance mental health support?",
      answers: [
        "Increased funding",
        "Better access to services",
        "Public awareness",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 50,
      question: "How can economic inequality be addressed?",
      answers: [
        "Progressive taxation",
        "Social programs",
        "Education",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 51,
      question: "What are key factors in effective disease prevention?",
      answers: [
        "Vaccination",
        "Healthy lifestyle",
        "Public health policies",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 52,
      question: "What are common challenges in remote learning?",
      answers: [
        "Access to technology",
        "Engagement",
        "Internet connectivity",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 53,
      question: "How can cities improve air quality?",
      answers: [
        "Green spaces",
        "Pollution controls",
        "Sustainable transportation",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 54,
      question: "What factors affect internet speed?",
      answers: [
        "Network infrastructure",
        "Bandwidth",
        "User location",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 55,
      question: "What are the benefits of biodiversity?",
      answers: [
        "Ecosystem stability",
        "Resource availability",
        "Climate regulation",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 56,
      question: "What are key elements of effective public health policies?",
      answers: [
        "Evidence-based practices",
        "Community involvement",
        "Health education",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 57,
      question: "How can digital literacy be improved?",
      answers: [
        "Education programs",
        "Access to technology",
        "Community initiatives",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 58,
      question: "What are common problems with healthcare accessibility?",
      answers: [
        "Cost",
        "Geographic barriers",
        "Insurance coverage",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 59,
      question: "What can be done to prevent environmental degradation?",
      answers: [
        "Sustainable practices",
        "Legislation",
        "Public awareness",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
    {
      id: 60,
      question: "What are the primary goals of economic development?",
      answers: [
        "Poverty reduction",
        "Economic growth",
        "Improved living standards",
        "All of the above",
      ],
      correctAnswer: "All of the above",
    },
  ],
};
