export const quiz = {
  totalQuestions: 34,
  questions: [
    {
      id: 1,
      question: "What is the SI unit of force?",
      answers: ["Newton (N)", "Kilogram (kg)", "Meter (m)", "Second (s)"],
      correctAnswer: "Newton (N)",
    },
    {
      id: 2,
      question: "Which of Newton's laws of motion describes the relationship between force, mass, and acceleration?",
      answers: ["First law", "Second law", "Third law", "None of the above"],
      correctAnswer: "Second law",
    },
    {
      id: 3,
      question: "What does the law of conservation of momentum state?",
      answers: ["Momentum is always zero", "Momentum is conserved in all interactions", "Momentum changes in every interaction", "Momentum is conserved only in elastic collisions"],
      correctAnswer: "Momentum is conserved in all interactions",
    },
    {
      id: 4,
      question: "Which quantity is a vector?",
      answers: ["Speed", "Distance", "Acceleration", "Energy"],
      correctAnswer: "Acceleration",
    },
    {
      id: 5,
      question: "What is the formula for kinetic energy?",
      answers: ["KE = 1/2 mv²", "KE = mgh", "KE = 1/2 mv", "KE = m/v"],
      correctAnswer: "KE = 1/2 mv²",
    },
    {
      id: 6,
      question: "What is the principle of superposition?",
      answers: ["Forces cancel each other out", "The net force is the sum of individual forces", "Forces are always equal and opposite", "Energy is conserved in a system"],
      correctAnswer: "The net force is the sum of individual forces",
    },
    {
      id: 7,
      question: "What is the acceleration due to gravity on Earth?",
      answers: ["9.8 m/s²", "10 m/s²", "8.9 m/s²", "9.8 km/s²"],
      correctAnswer: "9.8 m/s²",
    },
    {
      id: 8,
      question: "In a vacuum, all objects fall at the same rate regardless of their mass. This is an example of which principle?",
      answers: ["Archimedes' Principle", "Galileo's Principle", "Newton's First Law", "Conservation of Energy"],
      correctAnswer: "Galileo's Principle",
    },
    {
      id: 9,
      question: "Which force always opposes the motion of an object?",
      answers: ["Gravity", "Normal force", "Friction", "Tension"],
      correctAnswer: "Friction",
    },
    {
      id: 10,
      question: "What is the unit of work in the International System of Units (SI)?",
      answers: ["Joule (J)", "Newton (N)", "Watt (W)", "Pascal (Pa)"],
      correctAnswer: "Joule (J)",
    },
    {
      id: 11,
      question: "The centripetal force required to keep an object moving in a circular path is provided by?",
      answers: ["Friction", "Gravity", "Normal force", "Tension"],
      correctAnswer: "Tension",
    },
    {
      id: 12,
      question: "What type of energy is associated with an object in motion?",
      answers: ["Kinetic energy", "Potential energy", "Thermal energy", "Chemical energy"],
      correctAnswer: "Kinetic energy",
    },
    {
      id: 13,
      question: "Which of the following is a scalar quantity?",
      answers: ["Velocity", "Acceleration", "Force", "Speed"],
      correctAnswer: "Speed",
    },
    {
      id: 14,
      question: "What is the formula for gravitational potential energy?",
      answers: ["PE = mgh", "PE = 1/2 mv²", "PE = Fd", "PE = 1/2 kx²"],
      correctAnswer: "PE = mgh",
    },
    {
      id: 15,
      question: "Which law states that for every action, there is an equal and opposite reaction?",
      answers: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Law of Universal Gravitation"],
      correctAnswer: "Newton's Third Law",
    },
    {
      id: 16,
      question: "What is the term for the rate of change of velocity?",
      answers: ["Speed", "Acceleration", "Momentum", "Force"],
      correctAnswer: "Acceleration",
    },
    {
      id: 17,
      question: "In which type of collision is kinetic energy conserved?",
      answers: ["Elastic collision", "Inelastic collision", "Perfectly inelastic collision", "None of the above"],
      correctAnswer: "Elastic collision",
    },
    {
      id: 18,
      question: "What does the term 'work' mean in physics?",
      answers: ["Energy transferred by a force", "Force applied to an object", "Change in momentum", "Energy stored in an object"],
      correctAnswer: "Energy transferred by a force",
    },
    {
      id: 19,
      question: "Which principle states that energy cannot be created or destroyed, only transferred or transformed?",
      answers: ["Law of Conservation of Energy", "Newton's First Law", "Archimedes' Principle", "Law of Conservation of Momentum"],
      correctAnswer: "Law of Conservation of Energy",
    },
    {
      id: 20,
      question: "What is the SI unit of power?",
      answers: ["Watt (W)", "Joule (J)", "Newton (N)", "Pascal (Pa)"],
      correctAnswer: "Watt (W)",
    },
    {
      id: 21,
      question: "Which type of motion is described by a constant speed along a curved path?",
      answers: ["Uniform motion", "Accelerated motion", "Circular motion", "Random motion"],
      correctAnswer: "Circular motion",
    },
    {
      id: 22,
      question: "What does Hooke's Law describe?",
      answers: ["Elasticity of materials", "The force of gravity", "The conservation of momentum", "The rate of acceleration"],
      correctAnswer: "Elasticity of materials",
    },
    {
      id: 23,
      question: "The change in velocity per unit time is known as?",
      answers: ["Speed", "Acceleration", "Displacement", "Momentum"],
      correctAnswer: "Acceleration",
    },
    {
      id: 24,
      question: "What is the term for the energy an object has due to its position?",
      answers: ["Kinetic energy", "Potential energy", "Thermal energy", "Mechanical energy"],
      correctAnswer: "Potential energy",
    },
    {
      id: 25,
      question: "The force that acts between two surfaces in contact is called?",
      answers: ["Normal force", "Frictional force", "Gravitational force", "Tensional force"],
      correctAnswer: "Frictional force",
    },
    {
      id: 26,
      question: "What is the unit of frequency?",
      answers: ["Hertz (Hz)", "Watt (W)", "Joule (J)", "Newton (N)"],
      correctAnswer: "Hertz (Hz)",
    },
    {
      id: 27,
      question: "Which of the following is not a type of energy?",
      answers: ["Mechanical energy", "Kinetic energy", "Potential energy", "Magnetic energy"],
      correctAnswer: "Magnetic energy",
    },
    {
      id: 28,
      question: "What is the formula for calculating work done?",
      answers: ["W = Fd", "W = mgh", "W = 1/2 mv²", "W = F/v"],
      correctAnswer: "W = Fd",
    },
    {
      id: 29,
      question: "In which type of motion is the velocity changing at a constant rate?",
      answers: ["Uniform motion", "Accelerated motion", "Constant velocity motion", "Rotational motion"],
      correctAnswer: "Accelerated motion",
    },
    {
      id: 30,
      question: "What does the term 'momentum' refer to?",
      answers: ["Mass times velocity", "Force times distance", "Energy per unit time", "Speed times time"],
      correctAnswer: "Mass times velocity",
    },
    {
      id: 31,
      question: "What type of energy is associated with the motion of atoms and molecules?",
      answers: ["Thermal energy", "Kinetic energy", "Potential energy", "Electrical energy"],
      correctAnswer: "Thermal energy",
    },
    {
      id: 32,
      question: "What is the unit of electric current?",
      answers: ["Ampere (A)", "Volt (V)", "Ohm (Ω)", "Coulomb (C)"],
      correctAnswer: "Ampere (A)",
    },
    {
      id: 33,
      question: "Which principle states that the pressure in a fluid is exerted equally in all directions?",
      answers: ["Pascal's Principle", "Archimedes' Principle", "Boyle's Law", "Charles's Law"],
      correctAnswer: "Pascal's Principle",
    },
    {
      id: 34,
      question: "The amount of space an object occupies is called its?",
      answers: ["Volume", "Mass", "Density", "Weight"],
      correctAnswer: "Volume",
    },
  ],
};
